# Generated by Django 4.0.4 on 2022-04-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='сategory',
            new_name='сategoryType',
        ),
    ]
