# Generated by Django 4.0.3 on 2022-04-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_aaaa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='amount',
        ),
    ]
